BASE_URL_BINANCE = "https://fapi.binance.com"
BASE_URL_BITGET = "https://api.bitget.com"
BASE_URL_OKX = "https://www.okx.com"

MIN_VOLUME_BINANCE = 50_000_000
MIN_PERCENT = 0.2
PRICE_UPDATE_TIMEOUT = 10
PRICE_MAX_AGE_MS = 3000
MAX_TIMESTAMP_DIFF_MS = 500

DEPOSIT = 1000.0
RISK_PERC = 5.0